name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-container:
    name: Building  container image for Docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to Docker Hub
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
