name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-container:
    name: Building  container image for Docker
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1
      with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         repository: sanzats/angularapp
         tags: latest, ${{ github.run_number }}
